<a href="https://colab.research.google.com/github/nabilaaaa24/data_mining/blob/main/Latihan_Modul_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2>Latihan Prak. Data Mining<h2>
<h4>Modul 1<h2>

1. Buatlah sebuah list dengan 5 buah angka acak antara 1 sampai 10.

In [ ]:
# Tulis kode disini
import random

list1 = [random.randint(1, 10) for _ in range(5)]
print("List angka acak antara 1-10:", list1)

List angka acak antara 1-10: [4, 7, 9, 8, 2]


2. Ubah list tersebut menjadi tuple.

In [ ]:
# Tulis kode disini
import random

list1 = [random.randint(1, 10) for _ in range(5)]
tuple1 = tuple(list1)

print("Hasil tuple:", tuple1)

Hasil tuple: (7, 2, 8, 10, 4)


3. Tambahkan angka acak lainnya ke dalam tuple (ingat bahwa tuple tidak bisa diubah, jadi anda harus membuat tuple baru).

In [ ]:
# Tulis kode disini
import random

list1 = [random.randint(1, 10) for _ in range(5)]
tuple1 = tuple(list1)

print("Tuple awal:", tuple1)

tuple2 = random.randint(1, 10)
tuple_baru = tuple1 + (tuple2,)

print("setelah menambahkan angka acak baru:", tuple_baru)


Tuple awal: (7, 1, 8, 4, 8)
setelah menambahkan angka acak baru: (7, 1, 8, 4, 8, 9)


4. Buatlah sebuah fungsi yang menerima tuple angka dan mengembalikan tuple dengan elemen yang terurut.

In [ ]:
import random

def urutkan_tuple(tup):
    tuple_urut = tuple(sorted(tup))
    return tuple_urut

list1 = [random.randint(1, 10) for _ in range(5)]
tuple1 = tuple(list1)
tuple2 = urutkan_tuple(tuple1)

print(tuple1)
print("setelah diurutkan:", tuple2)

(3, 5, 8, 7, 6)
setelah diurutkan: (3, 5, 6, 7, 8)


5. Buat array Numpy 1D yang berisi 5 bilangan bulat acak dari 1 sampai 10.

In [ ]:
# Tulis kode disini
import numpy as np

array_random = np.random.randint(1, 10, size=5)
print(array_random)


[9 2 3 6 6]


6. Hitung mean, median, dan standar deviasi dari array tersebut.
Code Jawabannya:

In [ ]:
# Tulis kode disini
import numpy as np

array_random = np.random.randint(1, 10, size=5)
print(array_random)

# mean
mean_value = np.mean(array_random)
print("Mean:", mean_value)

# median
median_value = np.median(array_random)
print("Median:", median_value)

# standar deviasi
std_deviation_value = np.std(array_random)
print("Standar Deviasi:", std_deviation_value)

[9 9 7 6 9]
Mean: 8.0
Median: 9.0
Standar Deviasi: 1.2649110640673518


7. Buatlah array 2D (3x3) yang berisi angka acak.

In [ ]:
# Tulis kode disini
import numpy as np

array_2d = np.random.randint(1, 100, size=(3, 3))
print(array_2d)


[[20 71  1]
 [28  1 46]
 [13 71 32]]


8. Datar atau flatten array 2D tersebut menjadi array 1D.

In [ ]:
# Tulis kode disini
import numpy as np

array_2d = np.random.randint(1, 100, size=(3, 3))
print(array_2d)
array_1d = np.hstack(array_2d)
print("\nArray 1D:")
print(array_1d)

[[ 2 81  1]
 [29  1 92]
 [46 49 48]]

Array 1D:
[ 2 81  1 29  1 92 46 49 48]


9. Buatlah DataFrame Pandas sederhana yang berisi data nama, usia, dan kota dari 3 orang.

In [ ]:
# Tulis kode disini
import pandas as pd

data = {
    'Nama': ['Nabila', 'Yoongi', 'Minghao'],
    'Usia': [20, 30, 27],
    'Kota': ['Mojokerto', 'Daegu', 'Anshan']
}

df = pd.DataFrame(data)
print(df)

      Nama  Usia       Kota
0   Nabila    20  Mojokerto
1   Yoongi    30      Daegu
2  Minghao    27     Anshan


10. Tambahkan kolom 'Pekerjaan' ke DataFrame tersebut.

In [ ]:
# Tulis kode disini
import pandas as pd

data = {
    'Nama': ['Nabila', 'Yoongi', 'Minghao'],
    'Usia': [20, 30, 27],
    'Kota': ['Mojokerto', 'Daegu', 'Anshan']
}

df = pd.DataFrame(data)

df['Pekerjaan'] = ['Student', 'Rapper', 'Singer']

print(df)

      Nama  Usia       Kota Pekerjaan
0   Nabila    20  Mojokerto   Student
1   Yoongi    30      Daegu    Rapper
2  Minghao    27     Anshan    Singer


11. Ubahlah usia salah satu nama menjadi 31.

In [ ]:
# Tulis kode disini
import pandas as pd

data = {
    'Nama': ['Nabila', 'Yoongi', 'Minghao'],
    'Usia': [20, 30, 27],
    'Kota': ['Mojokerto', 'Daegu', 'Anshan']
}

df = pd.DataFrame(data)

df['Pekerjaan'] = ['Student', 'Rapper', 'Singer']
print(df)

df.loc[df['Nama'] == 'Yoongi', 'Usia'] = 31
print("\nDataFrame setelah perubahan:")
print(df)

      Nama  Usia       Kota Pekerjaan
0   Nabila    20  Mojokerto   Student
1   Yoongi    30      Daegu    Rapper
2  Minghao    27     Anshan    Singer

DataFrame setelah perubahan:
      Nama  Usia       Kota Pekerjaan
0   Nabila    20  Mojokerto   Student
1   Yoongi    31      Daegu    Rapper
2  Minghao    27     Anshan    Singer


12. Urutkan DataFrame berdasarkan usia dari yang muda ke yang tua.
Code Jawabannya:

In [ ]:
# Tulis kode disini
import pandas as pd

data = {
    'Nama': ['Nabila', 'Yoongi', 'Minghao'],
    'Usia': [20, 30, 27],
    'Kota': ['Mojokerto', 'Daegu', 'Anshan']
}

df = pd.DataFrame(data)

df['Pekerjaan'] = ['Student', 'Rapper', 'Singer']

print(df)

df_sorted = df.sort_values(by='Usia')
print("\nDataFrame setelah pengurutan berdasarkan usia:")
print(df_sorted)

      Nama  Usia       Kota Pekerjaan
0   Nabila    20  Mojokerto   Student
1   Yoongi    30      Daegu    Rapper
2  Minghao    27     Anshan    Singer

DataFrame setelah pengurutan berdasarkan usia:
      Nama  Usia       Kota Pekerjaan
0   Nabila    20  Mojokerto   Student
2  Minghao    27     Anshan    Singer
1   Yoongi    30      Daegu    Rapper
